# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20150426_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
