# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_useraddresses_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='new_purpose',
            new_name='purpose',
        ),
    ]
